name: ogs.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i --force
          cd back_end
          npm i --force
          pm2 stop 0
          pm2 start 0
          cd ..
          pm2 stop 2
          pm2 start 2
          pm2 save
